require:
  - rubocop-inhouse

inherit_gem:
  rubocop-inhouse:
    - config/default.yml

AllCops:
  TargetRubyVersion: 3.2

Lint/NumberConversion:
  Enabled: false

Lint/BinaryOperatorWithIdenticalOperands:
  Exclude:
    - spec/**/*.rb
